name: xconn
description: WAMP v2 Client and Router for Dart.
version: 0.1.0
repository: https://github.com/xconnio/xconn-dart
publish_to: none

environment:
  sdk: ^2.17.0

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  wampproto: ^0.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
