name: wamp
description: WAMP v2 Client for Dart.
version: 1.0.0
repository: https://github.com/xconnio/wamp.dart
publish_to: none

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  wampproto:
    git: https://github.com/xconnio/wampproto.dart

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
